<head>
  <title>Bootstrap 4 Website Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <link href="style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="jumbotron text-center" style="margin-bottom:0">
<img src="/thbs/img/logo-bt.png" height="42" width="42"/>
  <h1>My First Bootstrap 4 Page</h1> 
</div>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="#">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Resume</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contact</a>
      </li>    
    </ul>
  </div>  
</nav>

<div class="container" style="margin-top:30px">
  <div class="row">
    <div class="col-sm-4">
      <div class="linkedin">Rajat Goyal</div>
      <hr class="d-sm-none">
    </div>
    <div class="col-sm-8">
      <h1>About Me, September 5, 2018</h1>
      <div>
      <p>Hi, I am Rajat Goyal. I am having 6.5 years of IT experience. 
      Currently Working as a Senior Software Engineer for Torry Harris Business Solutions.</p>
      <a href="http://www.rajatgoyal.ga" target="_blank">Click on the link to know more</a></div>
  </div>
</div>
 